name: Compile changelogs

on:
  workflow_dispatch:
  schedule:
          git commit -m "Automatic changelog compile [ci skip]" -a || true
      - name: "Push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JAMIE }}
